# Makefile for building and cleaning the economancy player game

SOURCE=economancy.rkt

EXECUTABLE=economancy

all: $(EXECUTABLE)

$(EXECUTABLE): $(SOURCE)
	raco exe $(SOURCE)

clean:
	rm -f $(EXECUTABLE)

